### ISSUE TITLE
How install??

### ISSUE THREAD

**Issue by fran46** [live627/smf-steam-auth#2]
You can publish a little guide?

**Comment by fran46** [comment]
The package is installed: http://gyazo.com/09a1d8bace4e9d93c140688cb39b7c41
I've also added my API Key in: SteamAuth.english.php

How I can put the button on the login screen?

**Comment by live627** [comment]
API key should be input in Modification Settings in the admin panel.

**Comment by fran46** [comment]
Oh! thanks
I was doing wrong...
I was editing on the code (steamAuth.english.php)
this line:
$txt['steam_auth_api_key'] = 'Steam API key';
for
$txt['steam_auth_api_key'] = '8ASD5FASFASDF85A78ASDF'; (my steam api key)

I did it from the control panel and all good.
TY :d
